### ISSUE TITLE
SignOut from OpenID/AzureAD using OWIN causes invalid redirect

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#351] opened 2017-04-18 01:45 UTC
Button with following handler supposed to logout from Azure AD authenticated application.

```
<dot:Button Click="{command: Logout()}" Text="Logout" />
```

```
public void Logout()
{
    this.Context.GetOwinContext().Authentication.SignOut(
       OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);
}
```
It causes error:
DotVVM Debugger: Error XmlHttpRequest failed, maybe internet connection is lost or url is malformed

The redirect URL to (https://login.microsoftonline.com/xxx-xxx-xxx-xxx/oauth2/logout) seems to be sent (judging from the F12 console), but the redirect ends with error.

**Comment by tomasherceg** [comment] 2017-04-18 15:12
The problem is in the way how DotVVM handles redirects. Since the `Logout` method is called using AJAX, the server cannot return HTTP 302 because the browser will immediately do GET to a new URL return the HTML of the new page as the AJAX response which DotVVM can handle.

In the `Startup`, you need to have the following code in the configuration of OpenIdConnect provider:

```
                        RedirectToIdentityProvider = context =>
                        {
                            context.ProtocolMessage.RedirectUri = "<redirect uri>";

                            if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
                            {
                                var redirectUri = context.ProtocolMessage.CreateAuthenticationRequestUrl();
                                DotvvmRequestContext.SetRedirectResponse(DotvvmMiddleware.ConvertHttpContext(context.OwinContext), redirectUri, (int)HttpStatusCode.Redirect, true);
                                context.HandleResponse();
                            }
                            else if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                            {
                                var redirectUri = context.ProtocolMessage.CreateLogoutRequestUrl();
                                DotvvmRequestContext.SetRedirectResponse(DotvvmMiddleware.ConvertHttpContext(context.OwinContext), redirectUri, (int)HttpStatusCode.Redirect, true);
                                context.HandleResponse();
                            }
                            
                            return Task.FromResult(0);
                        },
```

In addition, you need to call `Context.InterruptRequest` after the `SignOut` call to tell DotVVM not to continue with the request processing.

```
            Context.GetAuthentication().SignOut(CookieAuthenticationDefaults.AuthenticationType, OpenIdConnectAuthenticationDefaults.AuthenticationType);
            Context.InterruptRequest();
```

I'll prepare a sample project for using AAD with DotVVM. Sorry about these issues.

**Comment by tomasherceg** [comment] 2017-04-18 18:35
The sample app is here: https://github.com/riganti/dotvvm-samples-azuread-auth

I am closing the issue. Feel free to reopen this one, or create another one if you hit into any issues.

**Comment by PavelBansky** [comment] 2017-04-21 06:06
I have looked at the sample and tried it out. I have run into a an issue, that ```this.Context``` is being Null in the ViewModel.

I just modified the DefaultViewModel constructor, like this

```
        public DefaultViewModel()
        {
            if (Context != null)
                Title = "Test";
        }
```
am I missing something, or the OpenIDAuthentication in the OWIN pipe line causes some problems?

**Comment by tomasherceg** [comment] 2017-04-21 09:30
It is strange - I have received an e-mail notification about a comment, but I cannot see it here. 

Here is the comment:

> I have looked at the sample and tried it out. I have run into a an issue, that this.Context is being Null in the ViewModel.
> I just modified the DefaultViewModel constructor, like this

        public DefaultViewModel()
        {
            if (Context != null)
                Title = "Test";
        }

> am I missing something, or the OpenIDAuthentication in the OWIN pipe line causes some problems?

My reply:

The `Context` is always null in the constructor. It is set in the framework right after the constructor is called.
Override the `Init` method and set the `Title` property there.

**Closed by tomasherceg** 2017-04-21 09:30 UTC
Labels: bug, Documentation

**Comment by fpamelard** [comment] 2018-05-23 15:31
Hi All,

I've got the same issue but I use the basic cookie authentification. Could you explain me how to achieve the signout without any errors?

Here is a part of my Startup.cs

app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Authentication/SignIn"),
                Provider = new CookieAuthenticationProvider()
                {
                    OnApplyRedirect = context =>
                    {
                        DotvvmAuthenticationHelper.ApplyRedirectResponse(context.OwinContext, context.RedirectUri);
                    }
                }
            });

Regards

**Comment by PavelBansky** [comment] 2018-05-23 18:48
I believe the solution is well described here:

**Comment by fpamelard** [comment] 2018-05-25 07:13
Thanks but the RedirectToIdentityProvider isn't included into the CookieAuthenticationProvider. Maybe, I'm wrong?

Please advice how to achieve this with the app.UseCookieAuthentication.

Cheers!
