### ISSUE TITLE
Dynamically added css class rewrites generated class name of DotVVM control

### ISSUE THREAD

**Issue by juratime** [riganti/dotvvm#336] opened 2017-03-14 09:09 UTC
`<RandomControl />`
class generated by dotvvm:
`class="dotvvm-bp-multiselect dotvvm-bp-default bp-control"`

`<RandomControl class="{value: List.Count == 0 ? "empty" : "nonempty"}" />`

New class attribute is just result of value binding, for example `class="empty"`, but `class="dotvvm-bp-multiselect dotvvm-bp-default bp-control empty"` was expected.

**Comment by djanosik** [comment] 2017-03-14 09:48
Hmm, we should probably use [class](https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/css.js#L2) binding for class attributes instead of `attr` binding.

**Comment by exyi** [comment] 2017-03-14 12:27
Using `Class-...` property group or setting the class attribute at compile-time (by Style) would solve the issue, combining value and binding at runtime is not supported and I don't see any reasonable way to do that.

**Comment by djanosik** [comment] 2017-03-14 12:30
@exyi We should support that to make it behave consistently. Right now, hard-coded value will append CSS class, but binding will replace it.

**Comment by exyi** [comment] 2017-03-15 12:34
@djanosik I agree it would be nice, but I'm afraid we would have to recompile the binding when combine it with a value, or use some custom binding handler like `dotvvm-more-attr: {class: ["value", " ", List().length ? "empty" : "nonempty"]}. Or do you have any other idea?

**Comment by djanosik** [comment] 2017-08-04 06:22
I think we should really fix this issue. There is no way to apply dynamic CSS classes to controls.

```html
<bp:Button class="{value: ClassFromDataSource}" />
```
It will overwrite all other CSS classes and the button will have no style.

**Comment by tomasherceg** [comment] 2017-08-05 08:27
Is there any other HTML attribute where you find this important? I am thinking of `style` - I know that they are bad, but people are using them too. 

I think we can do something like `control.Attributes.AppendOrSet(attributeName, valueOrBinding)`. 
The control developer would be able to use this method instead of just `control.Attributes[something] = something`, and we could update the view compiler to call this method too. 
The method will have a special handling for `class` and `style` attributes (and in the future maybe for more).

@exyi Is something like that possible? Because this is a problem for many of the Business Pack controls.

**Comment by exyi** [comment] 2017-08-05 10:00
I think that it would be possible to combine and recompile the bindings at runtime, so we could implement that, but I'm afraid that it will be either hidden performance killer (binding recompilation is not designed to be fast) or quite hard to do right. Actually, we don't have to update the view compiler because can already combine the attribute values (including bindings) correctly, the only problem is at runtime. So the problem could also be addressed by adding the attributes to BP controls using compile-time styles, but I understand that it's not very comfortable and the control then does not work when used in C# code, so you'd have to duplicate the logic. But it could be easier to find a way to apply styles to runtime created controls.

**Comment by djanosik** [comment] 2017-08-05 10:20
I think you don't need to recompile or combine binding. The solution is quite simple:

- Disable combining of values for all attributes other than `class` and `style`. For example, when you specify a `tabindex` attribute on control, it should overwrite the default value set by control.
- Don't use `attr` KO binding for `class` and `style` attributes. Instead use `class` and `style` bindings.

**Comment by exyi** [comment] 2017-08-07 12:56
@djanosik I'm afraid that rendering bindings in `class` attribute as knockout `css` binding won't solve the problem, as it will not behave correctly for expressions that can return multiple classes, and `style` probably won't work for similar expressions in `style` attribute. It may also be useful to be able to combine the bindings for other attributes - `Visible` and `IncludeInPage` properties seem to need that.

**Comment by djanosik** [comment] 2017-08-07 13:52
@exyi The `class` (not `css`) binding is designed to handle strings with multiple CSS classes. But you are right about the `style` binding. We would need to generate binding expression from string and somehow unset old values when the binding is changed.

**Comment by exyi** [comment] 2017-08-07 14:00
@djanosik  The problem is how to generate `style` binding expression from an expression that returns the string. It may look like `<div style="{value: MyProperty}"/>` with CSS in the viewmodel.

**Comment by djanosik** [comment] 2017-08-07 14:02
@exyi I see. Maybe we can create our own `style` binding?

**Comment by exyi** [comment] 2017-08-07 14:36
@djanosik I think that it would be simpler to have a general binding for concatenated attributes, like: `dotvvm-more-attr: {class: ["value", " ", List().length ? "empty" : "nonempty"]}`

**Comment by tomasherceg** [comment] 2018-06-08 15:17
How difficult would be to write this combining functionality, or use the binding handler to do that? 
If it is not so easy, I would keep this unsupported and close the issue.

**Comment by exyi** [comment] 2018-06-08 15:30
It's easy to combine the bindings, but you can't do that at runtime, because it has to be basically translated again, which is everything except fast. Maybe we could just combine the expressions and value when the attribute is rendered (by concatenating strings), but how would we decide if it's a hard-coded value or just pre-rendered value binding?

I don't know how hard is it to implement, as I don't know how to do it :). However, it would be very nice to have, the current behavior is pretty unsystematic.

**Closed** 2021-07-20 10:29 UTC
Labels: Framework, wontfix
