### ISSUE TITLE
It's not possible to have two SpaContentPlaceHolder on page

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#719] opened 2019-07-13 13:08 UTC
It's not able to have two `SpaContentPlaceHolder` in one page. I think this is not a bug it's design decision. But I except some exception when I have a page with two `SpaContentPlaceHolder`.

**Comment by tomasherceg** [comment] 2020-05-10 14:07
This is by design - there can be only one `SpaContentPlaceHolder` on a page. 
We should check whether a proper and meaningful exception is produced.

**Comment by acizmarik** [comment] 2020-09-22 16:16
Resolved by #847.

**Closed by acizmarik** 2020-09-22 16:16 UTC
Labels: Framework, enhancement, good first issue
