### ISSUE TITLE
Button onclick attribute is rendered after the script produced by the Click event

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#357] opened 2017-04-27 10:01 UTC
Consider the following code:

`<dot:Button Click="{command: something}" onclick="something else" />`

The `onclick` attribute value is placed after the script produced by the `Click` event, but the script ends with `return false` so the `onclick` code is not executed.

I don't think we should encourage users to use `onclick` attribute, we have postback handlers for this, but this behavior is not very intuitive. 

If there is an easy way to switch the order, I'd like to do it. 
If not, we should produce an error or warning that this is not supported.

**Comment by exyi** [comment] 2017-05-03 14:42
The problem is that atributes are automacally concatenated by HtmlWriter, I think we should leave this functionality only for certain atributes (class, style) and throw on the rest of them.

**Comment by tomasherceg** [comment] 2017-05-30 20:55
It depends whether the `writer.AddAttribute` is called before the `base.AddAttributesToRender` or after that. 

We should go through all DotVVM builtin controls and make sure that all `on`something attributes are rendered **after** the `base.AddAttributesToRender` controls.

Also, a test case should be added for this, at least for the `Button` and `LinkButton` controls.

**Comment by exyi** [comment] 2017-08-06 20:56
resolved by #411

**Closed by exyi** 2017-08-06 20:56 UTC
Labels: enhancement, Framework, up-for-grabs
