### ISSUE TITLE
Server-client transfer doesn't work with nested SignData properties

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#866] opened 2020-07-24 05:44 UTC
Hi,

another example where transfering data between server and client doesn't work:

 ```
BEHIND:

   public class TestViewModel : DotvvmViewModelBase
    {
        [Protect(ProtectMode.SignData)]
        public TestObj TestProp { get; set; } = new TestObj();

        public override Task PreRender()
        {
            if (!Context.IsPostBack)
            {
                this.TestProp = new TestObj()
                {
                    ID = 5,
                    Text = "Popis"
                };
            }

            return base.PreRender();
        }


        public void Postback() { }
    }


    public class TestObj
    {
        [Protect(ProtectMode.SignData)]
        public int ID { get; set; }

        public string Text { get; set; }
    }



HTML:

    ID = {{value: TestProp.ID}}<br />
    Text = {{value: TestProp.Text}}<br />

    <dot:Button Text="Postback" Click="{command: Postback()}"></dot:Button>
```

**Comment by acizmarik** [comment] 2020-07-24 13:13
Hi,
thanks for reporting. I am already working on your previous report #854 which basically covers the same issue.

The issue will be addressed in the following release (v2.5). Nesting `SignData` is not supported and we will add checks that unsure that users are properly notified. Originally, this feature was intended to be used only with simple properties. In general case, nesting the `ProtectModeAttribute` is not that easy and could lead to weird situations such as various combinations of `SignData` and `Encrypt` within nested objects.

Regarding your example: if you sign the property `TestProp`, all of its children are automatically treated as signed. Therefore, there is no need to sign the nested property `ID`.

**Comment by MichalOberreiter** [comment] 2020-07-25 07:14
Ok, I try to explain, why is necessary support nesting SignData.

Let's work with this class:

```
   public class Dog
   {
       [Protect(ProtectMode.SignData)]
       public int ID { get; set; }

       public string Name { get; set; }
   }
```
I have 2 pages "dogDetail.dothtml" and "dogRelations.dothtml". 
First page "DogDetail" contains form, where you CAN EDIT name of dog.
Second page "DogRelations" is used to create relations between dogs and dog shelters, where I dont want to change dog properties!

So, if I want to work only with one class "Dog", then i need to implement it like this: 
```
   dogDetail.dothtml

   [Protect(ProtectMode.None)]
   public Dog DogProperty { get; set; }
```
and
```
   dogRelations.dothtml

   [Protect(ProtectMode.SignData)]
   public Dog DogProperty { get; set; }
```

I hope that someone will finally get it. This is only way how to make web project truly secure. DotVVM goes wrong way, when allowing users write code, which can be changed from client side at default.
Right way is having everything signed (protected) and only if user want to make it editable, then he can use ProtectMode.None.

I know it's a difficult task, but please think about it. We are big fans of DotVVM, but without chance to have projects secure, we'll have to find better solutions.

**Comment by tomasherceg** [comment] 2020-07-25 12:04
In order to support signing nested properties, we'll need to do significant changes in the serializer which just cannot fit into 2.5 release. We plan to rewrite the serializer for DotVVM 3.0 (there are more reasons for this), and it will be easier to support more complex cases with signing. 

But I think that the main problem is not the signing - the main problem is using the same class for two completely different purposes.

On the DogDetail page, you can use the Dog class as you suggested. 
Btw, if you have the dog Id in the URL, there is no need to sign the Id property of the Dog object - the user can just change the URL to get any Id they want in there. You always need to validate whether the user can edit the particular dog.

On the DogRelation page, you can use a different class for displaying the info about the dog with signing. But preferably, you don't need to sign the values at all, and just not store the changes the user can make. The only thing you need to validate (no matter whether you are signing or not), is whether the user is allowed to edit the relationship between the particular dogs.

I understand that it is inconvenient to create more classes with similar members (especially if Dog is an entity from Entity Framework), but reusing the same class for two different purposes is even worse (especially from the long-term perspective and maintenance of the project).

DotVVM is not wrong in this - the approach is exactly the same as with any REST API and you'll face the same issues with any other web technology. Whenever you send anything to the client, you lose control over the data, and whenever you receive the data back from the client, you cannot trust them unless you verify they are correct. 
Unlike most of the web technologies that just don't care about it, DotVVM offers the signing feature to help with this a little (you can send something to the client and when you get it back, you can trust it hasn't been tampered with), but still, it is a generic problem of the client-server architecture and the basic principle cannot be magically solved. 
Even if you sign everything that you don't want the client to change, it is not enough to make the application secure unless you validate the data and verify permissions before saving. And with proper validation and permission checking, you'll find that the need for signing is very rare.

**Comment by MichalOberreiter** [comment] 2020-07-27 06:31
That's why we decided to change technology to DotVVM, because it has greater potential than other web technologies :-)
I just want to say, we would like to use full potential of this great feature, because we are trying to make development easier and because you know security better than we.

**Comment by tomasherceg** [comment] 2020-07-27 08:32
We've probably found a way how to support nesting without making significant changes in the serializer. However, there will still be a lot of combinations that are not permitted - for example, if you decide to Encrypt a part of the viewmodel, you cannot use signing in it (because encrypted objects are not serialized at all). Also, if you use Sign on a part of the viewmodel, you cannot override it to None in the object. However, if you Sign a part of the viewmodel and then use Sign inside, there should be no problem.
We'll let you know if the way we thought actually works.

**Closed** 2020-08-23 18:33 UTC
