### ISSUE TITLE
Source-codes to recompile DLL?

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#550] opened 2018-01-28 07:35 UTC
Hi,
I'm getting tired of fighting all the bugs... Is there source-code for the black-box DLL for business customers / boostrap customers?

Developer Express.... full source code. 
Telerik... Full source code.
CxJS... Full source code.
and other vendors same, full source code.

Reason.
I want to strip out Font-awseome, add Material Design icons, remove unneeded bootstrap CSS (via CSS remover), unneeded interfaces on the final build.

With DevEx, Terelik, I could do that. This I'm not sure, and I need to strip down the download size from ~ 1MB to 50kb. 

I also want to re-target data-pager and grid-view to use DataTables (somewhat missing here...), SlickGrid or HyperGrid.

**Comment by exyi** [comment] 2018-01-28 08:07
On Sun, 2018-01-28 at 07:35 +0000, Polywick Studio wrote:
> Hi,
> I'm getting tired of fighting all the bugs... Is there source-code
> for the black-box DLL for business customers / boostrap customers?

Not now. But it's not obfuscated, you can use ILSpy to have a look how does it work.

> Reason.
> I want to strip out Font-awseome, add Material Design icons, remove
> unneeded bootstrap CSS (via CSS remover), unneeded interfaces on the
> final build.

Hovewer, you can manipulate the JS and CSS, just re-register the dotvvm resources. You don't need recompilation

> I also want to re-target data-pager and grid-view to use DataTables
> (somewhat missing here...), SlickGrid or HyperGrid.

GridView does not have any problem with DataTables, the problem is that it can't be handled by dotvvm's JSON serializer. Which is open source. Note that we are not going to add support for this.

---

This is a bussiness decision, something I don't do and something we don't do on github, I'm going to close this issue.

**Closed by exyi** 2018-01-28 08:07 UTC
