### ISSUE TITLE
"Uncaught Error: ko.cleanNode: An already cleaned node was removed from the document" after upgrade 1.1 

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#331] opened 2017-03-08 13:46 UTC
Hello,

After upgrade from last rc to 1.1 rtm custom control (bootstrap-select) not working.

Its similar in dotvvm contrib repo. 

```
ko.bindingHandlers["bootstrap-select"] = {
  init: function (element, valueAccessor, allBindingsAccessor) {
    $(element).addClass('selectpicker').selectpicker({
      width: '100%',
      actionsBox:true,
      liveSearch: true,
      showSubtext: true,
      selectedTextFormat: 'count'
    });

    var refreshHandler = function () {
      $(element).selectpicker('refresh');
    };

    ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
      $(element).selectpicker('destroy');
    });
    dotvvm.events.afterPostback.subscribe(refreshHandler);
  },
  update: function (element, valueAccessor, allBindingsAccessor) {
    if ($(element).is('select')) {
      var selectPickerOptions = allBindingsAccessor().selectPickerOptions;
      if (typeof selectPickerOptions !== 'undefined' && selectPickerOptions !== null) {
        $(element).prop('disabled', selectPickerOptions.isDisabled());
        if (selectPickerOptions.title) {
          $(element).prop('title', selectPickerOptions.title());
        }
      }
      if (ko.isObservable(valueAccessor())) {
        if ($(element).prop('multiple') && $.isArray(ko.utils.unwrapObservable(valueAccessor()))) {
          ko.bindingHandlers.selectedOptions.update(element, valueAccessor);
        } else {
          ko.bindingHandlers.value.update(element, valueAccessor);
        }
      }
      $(element).selectpicker('refresh');
    }
  }
};
```

**Comment by exyi** [comment] 2017-03-08 17:01
The problem is that you are removing child DOM nodes in the knockout DisposeCallback which is unsupported. It worked before, because there wasn't the check, it was added by https://github.com/knockout/knockout/commit/d781ab503f4598891147115c99c35b31a9f260fb 

I'm not how to solve this, because there does not seem to be any other event, that will be okay to use and don't understand how to correctly destroy the selectpicker. Is it needed? I don't see the reason why would you have to remove it.

@djanosik This is probably the same issue as you have on BussinessPack, could you please try look at it?

**Comment by exyi** [comment] 2017-03-08 17:07
Update: It seems to be ok to add/remove elements after this one, exception is thrown only when you try to remove the former element. It means that the `.selectpicker('destroy')` has to remove some node before (or equal to) itself. Why does it do? BP ComboBox seems to do the same thing, why?

**Comment by djanosik** [comment] 2017-03-08 17:08
@exyi We don't remove nodes in dispose callback... so there should be no issue in BusinessPack, but I will take a look.

**Comment by exyi** [comment] 2017-03-08 17:12
Maybe this is another issue with the same error message :), @PadreSVK just showed me the same error on BP comboBox, so I thought it is the same cause

**Comment by djanosik** [comment] 2017-03-08 17:17
@exyi Interesting, maybe we do call $element.remove() in control.dispose. I can't look at the code right now. But it would make sense, calling .remove() in jQuery will free up all event handlers, so you don't have to care about them. I will take a look.

**Comment by martinsura** [comment] 2017-03-08 18:14
Can confirm: removing `(element).selectpicker('destroy')` works.

Question is, that no destroying component is good idea specially in SPA applications...

**Comment by djanosik** [comment] 2017-03-09 09:13
Ok, I have some good and some bad news.

Good news:

- Knockout [cleans](https://github.com/knockout/knockout/blob/master/src/utils.domNodeDisposal.js#L65) the element and all of its descendants
- It also calls jQuery's [cleanData](https://github.com/jquery/jquery/blob/master/src/manipulation.js#L285) which frees all event handlers and other data
- We don't need to care about this in BusinessPack

Bad news:

- `bootstrap-select` also removes some other elements in it's [destroy](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L1743) method that are not descendants of the element. They will not get cleaned-up properly if you don't call the `destroy` method.

@martinsura You may need to clean-up some elements yourself.

**Comment by tomasherceg** [comment] 2017-04-09 10:31
Closing because there is no reasonable way to solve this on DotVVM side. 
We need the newest Knockout version and removing the cleanNode check would cause another issued.

**Closed by tomasherceg** 2017-04-09 10:31 UTC
