### ISSUE TITLE
How to add DotVVM-boostrap to an existing project?

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#543] opened 2018-01-26 17:19 UTC
How do you add dot-vvm to an existing DotVVM project?

There is no instruction to add to existing.

The only way how is File > New Project > Wizard > [x] DotVVM Bootstrap.

**Comment by djanosik** [comment] 2018-01-26 17:21
Closing as duplicate of #539.

**Closed by djanosik** 2018-01-26 17:21 UTC

**Comment by djanosik** [comment] 2018-01-26 17:22
@PolywickStudio Please take a look at instructions in #539 .
