### ISSUE TITLE
Local Styles

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#400] opened 2017-07-24 17:12 UTC
The server-side styles in DotVVM can be defined only on the application scope. 
It would be useful to be able to define local styles too.

What about this?

```
dotvvmConfiguration.Styles.RegisterGroup("Style1", styles => 
{
    styles.Register<TextBox>(t => t.HasAncestor<FormGroup>())
         .SetAttribute("class", "form-control");
});
```

In a larger application, you would probably need to categorize the styles so they are not all in `DotvvmStartup.cs`. We can create a something like `StyleDefinition` base class with some auto-discovery mechanism - these would be registered automatically.

In the markup, you can import the styles like this:

```
<div Styles.Import="Styles1,Styles2">
</div>
```

**Comment by exyi** [comment] 2017-10-29 16:31
I agree that scoping the styles may be necessary, and I like this solution. I'd just add a `Styles.Clear` property, that would un-import all styles. And I'm not sure about the auto-discovery mechanism, I think that explicitly calling the initializers will be much more intuitive for a reader than unreferenced class. Or you can you asp.net core configuration if you want to fragment it, which is a standard solution.

**Comment by exyi** [comment] 2022-08-05 09:55
I think Styles.Tag is sufficient for this use case. I'll close this issue, since the problem is solvable by other means and I'd prefer not to add too many similar features.

**Closed by exyi** 2022-08-05 09:55 UTC
Labels: enhancement, Framework, proposal
