### ISSUE TITLE
DotVVM does not load when Repeater is added to page

### ISSUE THREAD

**Issue by vnwonah** [riganti/dotvvm#791] opened 2019-11-25 09:16 UTC
## Reproduction steps

- Create a Dotvvm Web Application(.Net Core)
- Add rename default files to Chat.dothtml and ChatViewModel, modify DotvvmStartup.cs as appropriate
- Create a Models folder and add a class Message as below

```
public class Message
{
    public string Username { get; set; }
    public string Text { get; set; }    
}
```

- Modify ChatViewModel as below
```
public class ChatViewModel : MasterPageViewModel
{
       
        public List<Message> Messages = new List<Message>();
        public bool SubmitVisible { get; set; } = true;
        [Required]
        public string Username { get; set;}

        [Required]
        public string Message { get; set; }

		public ChatViewModel()
		{
            
            
            
		}

        public async Task SendMessage()
        {
            if(!string.IsNullOrWhiteSpace(Username) && !string.IsNullOrWhiteSpace(Message))
            {
                Messages.Add(new Message { Username = Username, Text = Message }); 
            }
        }
}
```
- Modify Chat.dothtml as below
```
@viewModel DotvvmAnonyChat.ViewModels.ChatViewModel, DotvvmAnonyChat
@masterPage Views/MasterPage.dotmaster
    <dot:Content ContentPlaceHolderID="MainContent">
        <div class="page-center">
            <h1>AnonyChat on Dotvvm</h1>
            <div class="page-box">
                <dot:TextBox Text="{value: Username}" class="page-input" />
                <dot:TextBox Text="{value: Message}" class="page-input" />
                <dot:Button Text="Send Message" IsSubmitButton="true" Click="{command: SendMessage()}" class="page-button" name="SubmitButton" Visible="{value: SubmitVisible}" />
            </div>
            <div>
                <dot:Repeater DataSource="{value: Messages}">
                    <p>{{value: Text}}</p>
                </dot:Repeater>
            </div>
        </div>
    </dot:Content>
```
- Run Application

<b>Expected:</b> Application starts and displays controls on screen
<b>Actual:</b> Application starts up but request is never completed (loads indefinitely)

**Comment by tomasherceg** [comment] 2019-11-25 09:19
Please update to DotVVM 2.3.3 - the issue should be fixed there. 
The problem is that `public List<Message> Messages = new List<Message>();` is a field and not a property - it should be public `List<Message> Messages { get; set; } = new List<Message>();`.

**Comment by vnwonah** [comment] 2019-11-25 09:35
@tomasherceg seen thanks! does dotvvm support binding to static properties?

**Comment by tomasherceg** [comment] 2019-11-25 09:37
Yes, but you need to use Resource binding. There are some limitations to this approach, it is mostly used to access texts in resources. https://www.dotvvm.com/docs/tutorials/basics-resource-binding/2.0

**Closed** 2019-11-28 15:51 UTC
