### ISSUE TITLE
GridView EmptyDataTemplate overrides Visible=false attribute

### ISSUE THREAD

**Issue by ggrrin** [riganti/dotvvm#332] opened 2017-03-10 16:10 UTC
Hi,

I don't know whether following is a bug or feature. When GridView visible is set to false and there are no data in GridView, the EmptyDataTemplate is shown. It seems counter-intuitive to me.

**Comment by exyi** [comment] 2017-03-18 19:58
This is probably wrong, but the problem is more complex than you think... There two issue, both hackable but it would be nice to solve them nicely:
* EmptyData itself renders a `visible` binding and there is no reasonable way to combine them. Few days ago we spoke about this problem in context of html attributes with @djanosik (#336), and it seems to be more complex.
* Controls that render two or more html elements are kind-of-supported, but sometimes very broken - for example if you'd want to apply `Visible` property. `Postback.Update`, `Events.Click`, html attributes, ... would have similar problem and although it is possible to copy all of these properties to the second control, it is not trivial, very nice nor error-prone.

I'll probably close this issue as unsolvable in few days, if nobody will came with any idea and create a separate issue for multi-element controls.

**Comment by tomasherceg** [comment] 2017-07-24 11:55
Wrapping the control in `div` is a breaking change. The `GridView` it is not such big deal as the `Repeater` which has the same behavior.

I think we will need to adjust the `Visible` binding expression to combine the length of the collection and the control's `Visible` property.

**Comment by djanosik** [comment] 2017-07-24 12:13
`EmptyData` control uses `if` binding instead of `visible` binding for a while. Can we combine both bindings?

**Comment by tomasherceg** [comment] 2017-07-24 12:51
Possible conflict with `IncludeInPage` property.

**Closed** 2017-08-18 12:45 UTC
Labels: enhancement, Framework
