### ISSUE TITLE
Repeater causing a 500 error on PostBack 

### ISSUE THREAD

**Issue by jsaunders92** [riganti/dotvvm#530] opened 2017-12-31 02:22 UTC
Whenever I try to PostBack on any page that's using a repeater I'm getting an error 500 back in the console and the message "unhandled error during postback".. Any page without a repeater is fine and does the PostBack as it should.

**Comment by exyi** [comment] 2017-12-31 08:36
This means that an unhandled exception was thrown on the server during postback execution. Could you please have a look what does throw (it's logged to stdout on Asp.Net Core by default). Also note that when you would run dotvvm in Debugging environment it would give a nice error page.

**Comment by jsaunders92** [comment] 2017-12-31 10:35
It's actually not causing an error page at all, but debug mode is on, it will give me an error page for full errors but not for the PostBack issue. Also the stdout is only giving:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/tickets application/json 1623
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 128.881ms 500 text/html
```

So there's nothing really to go on. The only thing I do know is that it will only happen on a page with e repeater.

**Comment by exyi** [comment] 2017-12-31 10:58
That's pretty strange, could you please share how to reproduce it?

**Comment by jsaunders92** [comment] 2017-12-31 11:09
It's literally any page with a repeater and doing a PostBack. For example if you use the example repeater code and example command binding code from the documentation it happens for me. I know this because I tried assuming I might have messed something up. 

Is there not a way for the stdout to give me more details on what's causing the 500 error?

**Comment by tomasherceg** [comment] 2017-12-31 11:12
In which phase do you load the data for Repeater? Is it `Load` or `PreRender`? 
And how your DataSource looks like? Is it get/set property? Is there a `Bind` attribute on it?

**Comment by tomasherceg** [comment] 2017-12-31 11:13
And about the debugging - do you have a file called `Properties/launchSettings.json` in your project folder? Sometimes, this file is messed up. It should contain the following section which turns on the debug mode:

````
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
```

**Comment by exyi** [comment] 2017-12-31 11:28
> It's literally any page with a repeater and doing a PostBack. For example if you use the example repeater code and example command binding code from the documentation it happens for me. I know this because I tried assuming I might have messed something up.

I can only tell you that it work for me... There has to be some problem in the project configuration, could you please share a demo project?

> And about the debugging - do you have a file called
> `Properties/launchSettings.json` in your project folder? Sometimes,
> this file is messed up. It should contain the following section which
> turns on the debug mode:
> 
> ````
>       "environmentVariables": {
>         "ASPNETCORE_ENVIRONMENT": "Development"
>       }
> ```
By default, it logs the errors to stdout even in Production environment.

**Comment by jsaunders92** [comment] 2017-12-31 11:56
The env environment is already set to development anyway, it's the first thing I checked. My repeater code Is this 

```
<dot:Repeater  RenderSettings.Mode="Server" DataSource="{value: ticket}" RenderWrapperTag="false">
  
   <ItemTemplate >
        <tr >
           <td>{{value: a}}</td>
           <td>{{value: b}}</td>
            <td>{{value: c}} /td>
          <td data-visible="false">{{value: Priority}}</td>
        </tr>       
    </ItemTemplate>
</dot:Repeater>
```

I'm not using `Init`, `Load` or `PreRender` methods for the repeater. I am using a get set property. I was hoping for some verbosity than the stdout is giving me, it would be nice to know what exactly the error is.

**Comment by tomasherceg** [comment] 2017-12-31 12:00
How do you set the `ticket` property?

**Comment by jsaunders92** [comment] 2017-12-31 12:04
```
public class Ticket{
            public string A {get; set;}
            public string B {get; set;}
            public string C { get; set;}
            public string Priority {get; set;}

          public Ticket(string a, string b, string c, string priority)
        {
            A = a;
            B = b;
            C = c;
            Priority = priority;
        }
   }
```

Ignore the weird naming convention

**Comment by tomasherceg** [comment] 2017-12-31 12:10
Oh, I guess the constructor with the parameters is a problem. 
Can you also add a parameterless constructor in the class? 
Everything in viewmodel must be JSON-serializable, otherwise DotVVM is not able to transfer the viewmodel to the client and back.

**Comment by jsaunders92** [comment] 2017-12-31 13:05
haha, I feel a bit dumb now. I can't believe I missed that. Thank you! That fixed it :-)

**Comment by tomasherceg** [comment] 2017-12-31 13:07
No worries, but it is strange that a meaningful error message didn't appear. I will try to reproduce the issue.

**Comment by jsaunders92** [comment] 2017-12-31 13:33
Thank you, that's appreciated that. I tried to find different ways to get a more meaningful error message.

**Comment by exyi** [comment] 2018-01-06 11:37
Closing it as resolved. @jsaunders92 If you would figure out what was the problem with error messages, feel free to open another issue.

**Closed by exyi** 2018-01-06 11:37 UTC
