### ISSUE TITLE
StaticCommand - js error if handler returns null

### ISSUE THREAD

**Issue by cizfilip** [riganti/dotvvm#665] opened 2019-01-29 13:00 UTC
If we have simple static command inside view model
```
    public class TestViewModel
    {
        public string Test { get; set; }
    }

    public class DefaultViewModel : MasterPageViewModel
    {
        public TestViewModel Child { get; set; }

        [AllowStaticCommand]
        public static TestViewModel Test()
        {
            return null;
        }
    }
```

called in view:

```
<dot:Button Click="{staticCommand: Child = DefaultViewModel.Test()}">Test</dot:Button>
```

It throws javascript exception on client
```
TypeError: dotvvm.serialization.deserialize(...) is not a function
    at http://localhost:61453/:25:64
    at http://localhost:61453/dotvvmResource/dotvvm--internal/dotvvm--internal:1:23394
    at XMLHttpRequest.a.onreadystatechange (http://localhost:61453/dotvvmResource/dotvvm--internal/dotvvm--internal:1:34594)
```

eg. in generated onclick on button:
```
<input type="button" value="Test" onclick="dotvvm.applyPostbackHandlers(function(){return (function(a, b) {
	return new Promise(function(resolve) {
		dotvvm.staticCommandPostback(&quot;root&quot;, a, &quot;CfDJ8C6I8duQhZ1OoheDtOuw4Z8kKpdkQErJoxi5Xtu57BRs8BiyGGUsw4dtxwUX4twlhvGT6jWzzlHYjajop27gMm5FtQ3eL+3QG3z+kNIywL/6DZa5x0VVtXj17RkSZ41Ih3QqKHESue11ij7qrR+I9/YnZtBl/2aoyvSxqx9DHslUJgbGyVii0D9OtojmUe2geR4o6AM9XnBGtKhhM/b2BoyEMNniVa4UKRXyaaOPEkIP&quot;, [], function(r_0) {
			resolve(dotvvm.serialization.deserialize(r_0, b.$data.Child)());
		});
	});
}(this, ko.contextFor(this)))}.bind(this),this,[]);event.stopPropagation();return false;">
```

**Comment by quigamdev** [comment] 2019-02-23 13:23
@cizfilip Unfortunately, we are not able to reproduce this issue. Could you please provide more information about the version that you use. Or could you provide a demo app where this bug is present?

**Comment by quigamdev** [comment] 2019-03-03 19:31
I am closing this issue because I cannot reproduce. Feel free to reopen this issue if it is still a problem.

**Closed by quigamdev** 2019-03-03 19:31 UTC
Labels: Framework, bug
